def draw_grid_4x4():
    print("+ - - - - + - - - - + - - - - + - - - - +")
    print("|         |         |         |         |")
    print("|         |         |         |         |")
    print("|         |         |         |         |")
    print("|         |         |         |         |")
    print("+ - - - - + - - - - + - - - - + - - - - +")
    print("|         |         |         |         |")
    print("|         |         |         |         |")
    print("|         |         |         |         |")
    print("|         |         |         |         |")
    print("+ - - - - + - - - - + - - - - + - - - - +")
    print("|         |         |         |         |")
    print("|         |         |         |         |")
    print("|         |         |         |         |")
    print("|         |         |         |         |")
    print("+ - - - - + - - - - + - - - - + - - - - +")
    print("|         |         |         |         |")
    print("|         |         |         |         |")
    print("|         |         |         |         |")
    print("|         |         |         |         |")
    print("+ - - - - + - - - - + - - - - + - - - - +")

draw_grid_4x4()